---
title: "ExploratoryAnalysis"
author: "Haley Clapper"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#Load libraries

```{r libraries}

library(tidyverse)
library(lubridate)
library(cowplot)
library(here)
library(ggplot2)

getwd()

```

#Developing a plot of flood duration over time

```{r import flood data}

#Assign a variable to the processed data folder location
processed_data = "Output/ProcessedData_KEY"

flood_data <- read.csv(file=here("./ProcessedData/FloodData.csv"), stringsAsFactors = TRUE)

head(flood_data)

```

```{r}

# Convert END_DATE from factor to character
flood_data$END_DATE <- as.character(flood_data$END_DATE)

flood_data$END_DATE <- as.Date(paste0(flood_data$END_DATE, "-01"), format="%Y-%m-%d")

class(flood_data$END_DATE)

```

```{r plot flood duration vs month-year}

ggplot(flood_data, aes(x = END_DATE, y = Duration, color = Duration)) +
   geom_line() +
  scale_color_gradient(low = "blue", high = "orange") +
  scale_y_log10() +
  labs(x = "Date", y = "Flood Duration (hours)", title = "Flood Duration in Louisiana (1996-2022)", color = "Duration")+
  ylim(0, 800)

```

