---
title: "Spatial Analysis"
author: "Haley Clapper"
date: "2023-05-03"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
# Load libraries

library(tidyverse)
library(sf)
library(leaflet)
library(mapview)
library(here)
library(tidyverse, quietly = TRUE)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(dplyr)

```

```{r read in data}

# Read flood location data from CSV file
flood_data <- read.csv(file=here("./ProcessedData/FloodData.csv"), stringsAsFactors = TRUE)
                       
#Read in shp file for all states
shapes<- st_read('./RawData/SpatialLA/tl_2012_us_state.shp')

#Filter shp data for Louisiana
la_shape<-shapes%>%
  filter(STATEFP == 22)

#Setting projection
la_shape<-st_transform(la_shape, crs=26915)

head(la_shape)
                       
```

```{r remove NA}

#Wrangle flood data
flood_df<-flood_data%>%
  na.omit(BEGIN_LAT, BEGIN_LON)%>%
  select(BEGIN_LAT, BEGIN_LON, Duration)

colnames(flood_df)<-c("lat", "long", "duration")

head(flood_df)

```

```{r}

# Convert flood data to sf object with long-lat coordinates
flood_sf <- st_as_sf(flood_df, coords = c("long", "lat"), crs = 26915)

head(flood_sf)

```

#Map of Louisiana
```{r la plot}

#Plot of LA outline
la_plot<- ggplot() +
geom_sf(data = la_shape, fill = "white", color = "black") +
  theme_bw()

la_plot

```

#Map of flood locations by duration
```{r flood location plot}

#Plot of flood locations by duration
flood_locs<-ggplot()+
  geom_sf(data = flood_sf, aes(color = duration)) +
  labs(x = "Longitude", y = "Latitude", title = "Louisiana Floods by Duration (1996-2022)", color = "Flood Duration (hours)") +
  theme_void()

flood_locs

```

#This is the plot that shows up weird
```{r intersection plot}

ggplot() +
  geom_sf(data = la_shape)+
    geom_sf(data = flood_sf, aes(color = duration)) +
  labs(x = "Longitude", y = "Latitude", title = "Louisiana Floods by Duration (1996-2022)", color = "Flood Duration (hours)") +
  theme_void()

```

#Ignore this plot
```{r}

la_plot <- ggplot() +
  geom_sf(data = la_shape, fill = "white", color = "black") +
  geom_sf(data = flood_sf, aes(color = duration)) +
  labs(x = "Longitude", y = "Latitude", title = "Louisiana Floods by Duration (1996-2022)", color = "Flood Duration (hours)") +
  theme_void()

la_plot

```
