```{r}
#Loading packages
library(knitr)
library(tidyverse)
library(lubridate)
library(here)
library(cowplot)
library(ggplot2)
library(ggthemes)
library(zoo)
library(trend)
library(Kendall)
library(ggfortify)

#Setting working directory
here
getwd()

mytheme <- theme_wsj() + theme(plot.title = element_text(hjust = 0.5), 
   panel.grid.minor = element_line(color = 2,
   size = 0.25,
   linetype = 1),
  legend.position = "bottom", 
  axis.text = element_text(face="plain", size = 12),
  axis.title=element_text(size=14),
  title = element_text(size=12))

theme_set(mytheme)

```
```{r}

#Loading CSV file
FloodData <- read.csv("~/FinalProject/ProcessedData/FloodData.csv", stringsAsFactors = TRUE)

```




```{r}
#Creating all months
Months <- as.data.frame(x= seq(as.Date("1998/1/1"), as.Date("2022/12/31"), by = "month")) %>%
  rename("Date" = 1)

#Organizing by months 
FloodData.monthly <- FloodData %>% 
  group_by(Year, Month) %>%
  summarise(Duration.Mean = mean(Duration))
           
FloodData.monthly <- FloodData.monthly %>%
  mutate(Date = as.Date(as.yearmon(paste(Year, Month), "%Y %m")))

#Left join
FloodData.all.months <- left_join(x=Months, y=FloodData.monthly)

#Interpolation
FloodData_Interp <- FloodData.all.months %>%
  mutate(Duration.Mean = na.approx(Duration.Mean, na.rm=FALSE))

```
```{r}
monthly.FloodData.plot <- ggplot(FloodData_Interp, aes(x = Date, y = Duration.Mean)) + 
  labs(title = "Average Monthly Flood Duration in Louisiana",
       x = "Year",
       y = "Flood Duraton (Hours)") +
   ylim(c(0, 100)) +
  geom_smooth(method = lm, color = "black") +
  geom_line()

print(monthly.FloodData.plot)
```

```{r}
#Creating time series object
FloodData.ts <- 
  ts(FloodData_Interp$Duration.Mean, start = c(1998,1), end = c(2022,12), frequency=12)
#Decomposing monthly flood data
FloodData.ts_decomposed <- stl(FloodData.ts, s.window="periodic")

#Plotting decomoposed flood data
plot(FloodData.ts_decomposed)
```
```{r}
smk.test(FloodData.ts)
```


```{r}
FloodData.monthly.ts.Components <- as.data.frame(FloodData.ts_decomposed$time.series)

FloodData.monthly.ts.nonseasonal <- (FloodData.ts - FloodData.monthly.ts.Components$seasonal)

MannKendall(FloodData.monthly.ts.nonseasonal)

```
```{r}
autoplot(FloodData.monthly.ts.nonseasonal) + 
  labs(title = "Nonseasonal Average Monthly Flood Duration in Louisiana",
       x = "Year",
       y = "Flood Duraton (Hours)") +
   ylim(c(0, 100))
  

```


